(function () {
  'use strict';
  const $ = (s) => document.querySelector(s);
  const state = (window.__research = { state: 'idle', results: {}, saved: [], log: [], error: null, progress: null });

  function log(msg) {
    state.log.push(msg);
    const d = document.createElement('div');
    d.textContent = `${new Date().toLocaleTimeString()}  ${msg}`;
    $('#log').prepend(d);
  }

  async function save(path, text) {
    const r = await fetch(`api/save?path=${encodeURIComponent(path)}`, { method: 'POST', body: text, headers: { 'Content-Type': 'text/plain; charset=utf-8' } });
    if (!r.ok) throw new Error(`Saving ${path} failed: HTTP ${r.status}`);
    state.saved.push(path);
  }

  async function loadExisting() {
    try {
      const r = await fetch('results/research.json', { cache: 'no-store' });
      if (r.ok) return await r.json();
    } catch (e) { /* none yet */ }
    return { timeframes: {} };
  }

  // Production bundle for the dashboard: models, chosen configs, range calibration and live stats.
  function modelsBundle(all) {
    const out = { generatedAt: new Date().toISOString(), features: KAIROS.features.FEATURES.map((f) => f.id), timeframes: {} };
    for (const [tf, r] of Object.entries(all.timeframes)) {
      out.timeframes[tf] = {
        barMs: r.barMs, end: r.windows.end, holdoutStart: r.windows.holdoutStart,
        models: r.models, cone: r.cone,
        venues: Object.fromEntries(Object.entries(r.chosen).map(([id, c]) => [id, {
          label: c.label, H: c.H, tau: c.tau, costPct: c.costPct, longShort: c.longShort, verdict: c.verdict, probPositive: c.probPositive,
          holdout: c.holdout, perCoin: Object.fromEntries(c.perCoin.map((p) => [p.symbol, { verdict: p.verdict, holdout: p.holdout, buyHold: p.buyHold, probPositive: p.probPositive }])),
        }])),
        buyHold: r.buyHold.holdout,
        quality: Object.fromEntries(Object.entries(r.quality).map(([H, q]) => [H, { accuracy: q.holdout.accuracy, alwaysMajorityAccuracy: q.holdout.alwaysMajorityAccuracy, auc: q.holdout.auc, confident: q.holdout.confident }])),
        recent: r.recent,
      };
    }
    return out;
  }

  async function start() {
    const tfs = [...document.querySelectorAll('input[type=checkbox]:checked')].map((c) => c.value);
    if (!tfs.length) return;
    $('#run').disabled = true;
    state.state = 'running';
    const all = await loadExisting();
    const worker = new Worker('js/research-worker.js');
    worker.onmessage = async (e) => {
      const m = e.data;
      if (m.type === 'progress') {
        state.progress = m;
        const idx = tfs.indexOf(m.tf);
        const pct = ((idx + m.pct / 100) / tfs.length) * 100;
        $('#bar').style.width = pct.toFixed(1) + '%';
        $('#status').textContent = m.msg;
      } else if (m.type === 'result') {
        all.timeframes[m.tf] = m.result;
        state.results[m.tf] = m.result;
        const c = m.result.chosen;
        log(`${m.result.label} finished in ${m.result.durationSec}s — spot: H=${c.spot.H} tau=${c.spot.tau} holdout Sharpe ${c.spot.holdout.sharpe} (${c.spot.verdict}); futures: H=${c.perp.H} tau=${c.perp.tau} holdout Sharpe ${c.perp.holdout.sharpe} (${c.perp.verdict}); buy & hold ${m.result.buyHold.holdout.sharpe}`);
        try {
          all.generatedAt = new Date().toISOString();
          all.settings = KAIROS.research.SETTINGS;
          const json = JSON.stringify(all);
          await save('results/research.json', json);
          await save('results/research.js', `// Auto-generated by research.html\nwindow.KAIROS_RESEARCH = ${json};\n`);
          await save('config/models.js', `// Auto-generated by research.html — live models used by the dashboard\nwindow.KAIROS_MODELS = ${JSON.stringify(modelsBundle(all))};\n`);
          log(`Saved results for ${m.result.label}`);
        } catch (err) {
          state.error = err.message;
          log(err.message + ' (is serve.cmd running?)');
        }
      } else if (m.type === 'done') {
        worker.terminate();
        state.state = 'done';
        $('#status').textContent = 'Done.';
        $('#bar').style.width = '100%';
        $('#run').disabled = false;
      } else if (m.type === 'error') {
        worker.terminate();
        state.state = 'error';
        state.error = m.stack || m.message;
        $('#status').textContent = 'Error: ' + m.message;
        log(m.stack || m.message);
        $('#run').disabled = false;
      }
    };
    worker.postMessage({ timeframes: tfs });
    log(`Training ${tfs.join(', ')}`);
  }

  $('#run').addEventListener('click', start);
  const q = new URLSearchParams(location.search);
  if (q.has('tf')) document.querySelectorAll('input[type=checkbox]').forEach((c) => (c.checked = q.get('tf').split(',').includes(c.value)));
  if (q.has('autorun')) start();
})();
