(function () {
  'use strict';
  const K = window.KAIROS, Sg = K.signal;
  const $ = (s) => document.querySelector(s);
  // Results from an older engine (different signals or result shape) are dropped rather than mixed in.
  const prior = Object.fromEntries(Object.entries((window.SIGNAL_TUNING && window.SIGNAL_TUNING.timeframes) || {}).filter(([, r]) => r.config && r.config.weights && r.config.weights.length === Sg.NS && r.config.combos && Array.isArray(r.cellTable)));
  const state = (window.__tune = { state: 'idle', results: prior, saved: [], log: [], error: null, progress: null });
  const MINUS = '−';
  const ok = (v) => v !== null && v !== undefined && Number.isFinite(v);
  const pct = (v, d = 1) => (ok(v) ? (v > 0 ? '+' : v < 0 ? MINUS : '') + Math.abs(v * 100).toFixed(d) + '%' : '—');
  const pctAbs = (v, d = 1) => (ok(v) ? (v * 100).toFixed(d) + '%' : '—');
  const num = (v, d = 2) => (ok(v) ? (v < 0 ? MINUS : '') + Math.abs(v).toFixed(d) : '—');
  const signed = (v, d = 2) => (ok(v) ? (v > 0 ? '+' : v < 0 ? MINUS : '') + Math.abs(v).toFixed(d) : '—');
  const date = (iso) => new Date(iso).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric', timeZone: 'UTC' });
  const dt = (t) => new Date(t).toLocaleString('en-US', { month: 'short', day: 'numeric', year: '2-digit', hour: '2-digit', minute: '2-digit', hour12: false });
  const esc = (s) => String(s).replace(/[&<>"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]));
  const fmtPrice = (v) => { const a = Math.abs(v), d = a >= 10 ? 2 : a >= 1 ? 3 : 5; return v.toLocaleString('en-US', { minimumFractionDigits: d, maximumFractionDigits: d }); };
  const comboLabel = Sg.comboLabel;
  const fmtTheta = K.tuner.fmtTheta;

  function log(msg) {
    state.log.push(msg);
    const d = document.createElement('div');
    d.textContent = `${new Date().toLocaleTimeString()}  ${msg}`;
    $('#log').prepend(d);
  }

  async function save(path, text) {
    const r = await fetch(`api/save?path=${encodeURIComponent(path)}`, { method: 'POST', body: text, headers: { 'Content-Type': 'text/plain; charset=utf-8' } });
    if (!r.ok) throw new Error(`Saving ${path} failed: HTTP ${r.status}`);
    state.saved.push(path);
  }

  // Compact bundle for the live terminal.
  function configBundle(all) {
    const out = { generatedAt: new Date().toISOString(), signals: Sg.SIGNALS.map((s) => s.id), timeframes: {} };
    for (const [tf, r] of Object.entries(all)) {
      out.timeframes[tf] = {
        barMs: r.barMs, windows: r.windows, symbols: r.symbols, config: r.config, mlModel: r.mlModel,
        holdout: r.compare.tuned.holdout, holdoutRecent: r.compare.tuned.holdoutRecent, holdoutFixed: r.compare.fixed.holdout, holdoutPerBar: r.compare.tuned.perBarHoldout, holdoutMakerFees: r.holdoutMakerFees,
        baselineHoldout: r.compare.baseline.holdout, mlOnlyHoldout: r.compare.mlOnly.holdout,
        cellTable: r.cellTable.map((c) => ({ cell: c.cell, key: c.key, fallback: c.fallback, trainTrades: c.trainTrades, trainAvgR: c.trainAvgR, holdout: c.holdout ? { trades: c.holdout.trades, avgR: c.holdout.avgR, winRate: c.holdout.winRate } : null })),
      };
    }
    return out;
  }

  async function persist() {
    const all = { generatedAt: new Date().toISOString(), settings: K.tuner.SETTINGS, timeframes: state.results };
    const json = JSON.stringify(all);
    await save('results/tuning.json', json);
    await save('results/tuning.js', `// Auto-generated by tune.html\nwindow.SIGNAL_TUNING = ${json};\n`);
    await save('config/signal.js', `// Auto-generated by tune.html — live signal engine configuration\nwindow.SIGNAL_CONFIG = ${JSON.stringify(configBundle(state.results))};\n`);
  }

  async function start() {
    const tfs = [...document.querySelectorAll('input[type=checkbox]:checked')].map((c) => c.value);
    if (!tfs.length) return;
    const coinSet = document.querySelector('input[name=coins]:checked').value;
    const symbols = coinSet === 'all' ? K.tuner.SETTINGS.mlSymbols : K.tuner.SETTINGS.symbols;
    $('#run').disabled = true;
    state.state = 'running';
    const worker = new Worker('js/tune-worker.js');
    worker.onmessage = async (e) => {
      const m = e.data;
      if (m.type === 'progress') {
        state.progress = m;
        const idx = tfs.indexOf(m.tf);
        $('#bar').style.width = (((idx + m.pct / 100) / tfs.length) * 100).toFixed(1) + '%';
        $('#status').textContent = m.msg;
      } else if (m.type === 'result') {
        state.results[m.tf] = m.result;
        const r = m.result, c = r.compare;
        log(`${r.label} done in ${r.durationSec}s — base ${comboLabel(r.config.base)}, bar ${fmtTheta(r.config.theta)}, ${r.config.variant} weights, ${r.config.adaptive ? 'adaptive exits' : 'fixed exits'}. Holdout: final ${signed(c.tuned.holdout.avgR)}R/trade over ${c.tuned.holdout.trades} trades (win ${pctAbs(c.tuned.holdout.winRate)}), fixed exits ${signed(c.fixed.holdout.avgR)}R, equal weights ${signed(c.baseline.holdout.avgR)}R, ML-only ${signed(c.mlOnly.holdout.avgR)}R`);
        try { render(); } catch (err) { log('Render failed: ' + err.message); }
        try {
          await persist();
          log('Saved config/signal.js and results/tuning.js');
        } catch (err) {
          state.error = err.message;
          log(err.message + ' (is serve.cmd running?)');
        }
      } else if (m.type === 'done') {
        worker.terminate();
        state.state = 'done';
        $('#status').textContent = 'Done.';
        $('#bar').style.width = '100%';
        $('#run').disabled = false;
      } else if (m.type === 'error') {
        worker.terminate();
        state.state = 'error';
        state.error = m.stack || m.message;
        $('#status').textContent = 'Error: ' + m.message;
        log(m.stack || m.message);
        $('#run').disabled = false;
      }
    };
    worker.postMessage({ timeframes: tfs, symbols });
    log(`Tuning ${tfs.join(', ')} on ${symbols.length} coins`);
  }

  // ---------------- report ----------------
  let current = null;
  function table(headers, rows, hlIndex) {
    return `<div class="table-wrap"><table class="t"><thead><tr>${headers.map((h) => `<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.map((r, i) => `<tr class="${i === hlIndex ? 'hl' : ''}">${r.map((c) => `<td>${c}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
  }
  const cls = (v) => (v > 0 ? 'g' : v < 0 ? 'r' : '');
  const STAT_HEAD = ['Formula', 'Trades', 'Win rate', 'Avg R', 'Total R', 'Profit factor', 't-stat', 'Next-candle acc.', 'Return @1% risk', 'Return ¼-Kelly'];
  const statRow = (label, s, breakeven) => [label, s.trades, `<span class="${!ok(breakeven) || s.winRate >= breakeven ? 'g' : 'r'}">${pctAbs(s.winRate)}</span>`, `<span class="${cls(s.avgR)}">${signed(s.avgR, 3)}R</span>`, `<span class="${cls(s.totalR)}">${signed(s.totalR, 1)}R</span>`, num(s.profitFactor), num(s.tstat), pctAbs(s.accuracy), `<span class="${cls(s.return1pct)}">${pct(s.return1pct)}</span>`, `<span class="${cls(s.returnKelly)}">${pct(s.returnKelly)}</span>`];

  function equitySvg(box, pts, t0, t1) {
    if (!pts.length) { box.innerHTML = '<div class="empty">No holdout trades.</div>'; return; }
    const W = Math.max(320, box.clientWidth), H = box.clientHeight || 260, m = { l: 8, r: 54, t: 10, b: 22 };
    let lo = Math.min(0, ...pts.map((p) => p.R)), hi = Math.max(0, ...pts.map((p) => p.R));
    const pad = (hi - lo) * 0.08 || 1;
    lo -= pad; hi += pad;
    const x = (t) => m.l + ((t - t0) / (t1 - t0)) * (W - m.l - m.r), y = (v) => m.t + (1 - (v - lo) / (hi - lo)) * (H - m.t - m.b);
    const ticks = [];
    const step = Math.pow(10, Math.floor(Math.log10((hi - lo) / 4)));
    for (let v = Math.ceil(lo / step) * step; v <= hi; v += step) ticks.push(v);
    const poly = [[t0, 0], ...pts.map((p) => [p.t, p.R])].map(([t, v]) => `${x(t).toFixed(1)},${y(v).toFixed(1)}`).join(' ');
    const months = [];
    for (let d = new Date(t0); d.getTime() < t1; d.setUTCMonth(d.getUTCMonth() + 3)) months.push(d.getTime());
    box.innerHTML = `<svg viewBox="0 0 ${W} ${H}">
      ${ticks.map((v) => `<line x1="${m.l}" x2="${W - m.r}" y1="${y(v)}" y2="${y(v)}" stroke="${v === 0 ? 'rgba(255,255,255,.25)' : 'rgba(255,255,255,.06)'}"/><text x="${W - m.r + 6}" y="${y(v) + 3.5}">${signed(v, 0)}R</text>`).join('')}
      ${months.map((t) => `<text x="${x(t)}" y="${H - 6}" text-anchor="middle">${new Date(t).toLocaleDateString('en-US', { month: 'short', year: '2-digit', timeZone: 'UTC' })}</text>`).join('')}
      <polyline points="${poly}" fill="none" stroke="#f5c518" stroke-width="1.8" stroke-linejoin="round"/>
    </svg>`;
  }

  function render() {
    const tfs = ['1h', '4h', '1d'].filter((tf) => state.results[tf]);
    if (!tfs.length) { $('#report').innerHTML = ''; return; }
    if (!current || !state.results[current]) current = tfs.includes('4h') ? '4h' : tfs[0];
    const r = state.results[current], c = r.config, cmp = r.compare, be = c.base.breakeven, S = K.tuner.SETTINGS;
    const fin = cmp.tuned.holdout, rec = cmp.tuned.holdoutRecent, mk = r.holdoutMakerFees;
    const verdictCls = fin.avgR > 0.05 && fin.tstat > 1.5 ? 'good' : fin.avgR > 0 && fin.tstat > 0.75 ? 'meh' : 'bad';
    const verdictText = verdictCls === 'good'
      ? `On unseen data the final formula made <b>${signed(fin.avgR, 3)}R per trade</b> after fees over ${fin.trades} trades (t = ${num(fin.tstat)}). That is a real, if modest, edge.`
      : verdictCls === 'meh'
        ? `On unseen data the final formula made <b>${signed(fin.avgR, 3)}R per trade</b> after fees over ${fin.trades} trades (t = ${num(fin.tstat)}): positive but too small to distinguish from luck. Treat calls as information, not a system.`
        : `On unseen data the final formula made <b>${signed(fin.avgR, 3)}R per trade</b> after fees over ${fin.trades} trades (t = ${num(fin.tstat)}): no reliable edge. Treat calls as information, not a system.`;
    const pc = r.policyCheck;

    $('#report').innerHTML = `
      <div class="tabs">${tfs.map((tf) => `<button type="button" role="tab" aria-selected="${tf === current}" data-tf="${tf}">${state.results[tf].label}</button>`).join('')}</div>
      <div class="verdict ${verdictCls}">${verdictText}${c.variant === 'equal' ? ' On the validation slice, tuning did not beat plain equal weights for this timeframe, so the final formula uses equal weights.' : ''} ${c.adaptive ? `Adaptive exits beat the fixed setup on validation (t ${num(pc.validationPolicy.tstat)} vs ${num(pc.validationFixed.tstat)}) and are used.` : `Adaptive exits did not beat the fixed setup on validation (t ${num(pc.validationPolicy.tstat)} vs ${num(pc.validationFixed.tstat)}), so the fixed setup is used.`} Direction of the next candle was right <b>${pctAbs(cmp.tuned.perBarHoldout.allAccuracy)}</b> of the time on every bar. ${ok(be) ? `Breakeven win rate at 1:${c.base.rr} is ${pctAbs(be)}; actual ${pctAbs(fin.winRate)}.` : ''} <b>Most recent slice</b> (${date(r.windows.recentStart)} → today): <b>${signed(rec.avgR, 3)}R</b> per trade over ${rec.trades} trades. At maker fees (${c.makerFeePct}%): ${signed(mk.avgR, 3)}R per signal bar instead of ${signed(cmp.tuned.perBarHoldout.avgR, 3)}R.</div>

      <section class="pane"><div class="pane-head"><span class="pane-title">Before vs after · ${r.label} · holdout ${date(r.windows.holdoutStart)} → ${date(r.windows.end)} · after fees · one position per coin at a time</span></div>
      <div class="pane-body">${table(STAT_HEAD,
        [statRow('Equal weights (start)', cmp.baseline.holdout, be), statRow('ML model only', cmp.mlOnly.holdout, be), statRow('Final weights, fixed exits', cmp.fixed.holdout, be), statRow(cmp.tuned.label, cmp.tuned.holdout, be), statRow(`${cmp.tuned.label} · since ${date(r.windows.recentStart)}`, rec, be)], 3)}
      <p class="note">Same formulas on the train period (where they were fitted, so they are flattered):</p>
      ${table(STAT_HEAD,
        [statRow('Equal weights (start)', cmp.baseline.train, be), statRow('ML model only', cmp.mlOnly.train, be), statRow('Final weights, fixed exits', cmp.fixed.train, be), statRow(cmp.tuned.label, cmp.tuned.train, be)], 3)}
      <p class="note">"Return ¼-Kelly" risks a quarter of the Kelly fraction implied by each trade's calibrated probability and payoff, capped at ${(S.kellyCap * 100).toFixed(0)}% of the account per trade (average risk on holdout: ${pctAbs(fin.avgRisk, 2)}).</p>
      </div></section>

      <div class="grid2">
        <section class="pane"><div class="pane-head"><span class="pane-title">Holdout equity · cumulative R · all coins</span></div>
        <div class="pane-body"><div class="chart-box" id="eq"></div></div></section>
        <section class="pane"><div class="pane-head"><span class="pane-title">Chosen setup</span></div>
        <div class="pane-body">
          <div class="stat-grid">
            <div class="stat"><div class="k">Base exit setup</div><div class="v">${comboLabel(c.base)}</div><div class="s">max ${c.maxBars} bars · ${c.adaptive ? 'adaptive per situation' : 'fixed'}</div></div>
            <div class="stat"><div class="k">Strong-call bar</div><div class="v">${fmtTheta(c.theta)}</div><div class="s">of max score ${c.maxScore} · ${c.variant} weights</div></div>
            <div class="stat"><div class="k">Holdout trades</div><div class="v">${fin.trades}</div><div class="s">${pctAbs(fin.tpRate, 0)} target · ${pctAbs(fin.slRate, 0)} stop · ${pctAbs(fin.trailRate, 0)} trailed out · ${pctAbs(fin.timeoutRate, 0)} timeout · ${pctAbs(fin.longShare, 0)} long</div></div>
            <div class="stat"><div class="k">Max drawdown</div><div class="v r">${num(fin.maxDrawdownR, 1)}R</div><div class="s">avg hold ${num(fin.avgBars, 1)} bars</div></div>
          </div>
          <p class="note">Fit rows ${r.rows.fit.toLocaleString()} (${date(r.windows.trainStart)} → ${date(r.windows.validationStart)}) · validation rows ${r.rows.validation.toLocaleString()} (→ ${date(r.windows.holdoutStart)}) · holdout rows ${r.rows.holdout.toLocaleString()} · ML input: ${r.mlFits} weekly refits, horizon ${c.H} bars · coins ${r.symbols.map((s) => s.replace('USDT', '')).join(', ')}.</p>
        </div></section>
      </div>

      <section class="pane"><div class="pane-head"><span class="pane-title">Exit policy · which stop / target each situation gets</span></div>
      <div class="pane-body">
        <p class="note" style="margin:0 0 10px">For every situation the signal fires in (volatility regime × direction × strength), the exit setup with the best lower-confidence-bound R on the train period. ${c.adaptive ? 'In use.' : 'Not in use: it did not beat the fixed setup on validation, shown for information.'} Holdout columns are the final formula's actual trades in that situation.</p>
        ${table(['Situation', 'Exit setup', 'Train trades', 'Train avg R', 'Base setup avg R', 'Holdout trades', 'Holdout win', 'Holdout avg R'], r.cellTable.map((x) => [x.label, `${comboLabel(c.combos[x.key])}${x.fallback ? ' <span class="dim">(fallback)</span>' : ''}`, x.trainTrades, `<span class="${cls(x.trainAvgR)}">${signed(x.trainAvgR, 3)}</span>`, signed(x.trainBaseAvgR, 3), x.holdout ? x.holdout.trades : '—', x.holdout ? pctAbs(x.holdout.winRate) : '—', x.holdout ? `<span class="${cls(x.holdout.avgR)}">${signed(x.holdout.avgR, 3)}</span>` : '—']))}
      </div></section>

      <div class="grid2">
        <section class="pane"><div class="pane-head"><span class="pane-title">Every exit setup · final weights · signal bars</span></div>
        <div class="pane-body">${table(['Exit setup', 'Breakeven', 'Train avg R', 'Holdout bars', 'Holdout win', 'Holdout avg R', 'Holdout t'], Object.values(c.combos).slice().sort((a, b) => b.holdout.avgR - a.holdout.avgR).map((cb) => [comboLabel(cb) + (cb.key === c.base.key ? ' ✓' : ''), ok(cb.breakeven) ? pctAbs(cb.breakeven, 0) : '—', signed(cb.train.avgR, 3), cb.holdout.trades, pctAbs(cb.holdout.winRate), `<span class="${cls(cb.holdout.avgR)}">${signed(cb.holdout.avgR, 3)}</span>`, num(cb.holdout.tstat)]), Object.values(c.combos).slice().sort((a, b) => b.holdout.avgR - a.holdout.avgR).findIndex((cb) => cb.key === c.base.key))}
          <p class="note">Every bar the formula fires on, each exit applied. These are the numbers the terminal shows when you override the exit in the Parameters panel.</p>
        </div></section>
        <section class="pane"><div class="pane-head"><span class="pane-title">Setup selection · fit → validation</span></div>
        <div class="pane-body">${table(['Exit setup', 'Fit t (tuned)', 'Val. t (tuned)', 'Val. t (equal)', 'Val. trades'], r.selection.map((x) => [`${comboLabel(x)}${x.chosen ? ' ✓ ' + x.chosen : ''}`, num(x.fitObjective), `<span class="${x.chosen === 'tuned' ? 'y' : ''}">${x.tuned.val.objective < -1e8 ? '<span class="dim">too few</span>' : num(x.tuned.val.tstat)}</span>`, `<span class="${x.chosen === 'equal' ? 'y' : ''}">${x.equal.val.objective < -1e8 ? '<span class="dim">too few</span>' : num(x.equal.val.tstat)}</span>`, `${x.tuned.val.trades} / ${x.equal.val.trades}`]), r.selection.findIndex((x) => x.chosen))}
          <p class="note">Each setup was tuned on the fit half and judged on the validation half against plain equal weights; the best out-of-sample variant won and was refitted on the whole train period.</p>
        </div></section>
      </div>

      <div class="grid2">
        <section class="pane"><div class="pane-head"><span class="pane-title">Weights that won · train importance</span></div>
        <div class="pane-body">${table(['Signal', 'Group', 'Weight', 'Objective lost if removed'],
          r.importance.slice().sort((a, b) => Math.abs(b.weight) - Math.abs(a.weight) || b.loss - a.loss).map((x) => [x.label, x.group, `<span class="${cls(x.weight)}">${signed(x.weight, 2)}</span>`, x.weight ? num(x.loss) : '<span class="dim">dropped</span>']))}
          <p class="note">Positive weight = the signal is used as defined (bullish reading → long). Negative = the tuner found it works better inverted. ${r.pruned.length ? 'Dropped as weak: ' + r.pruned.join(', ') + '.' : 'Nothing was dropped.'}</p>
        </div></section>
        <section class="pane"><div class="pane-head"><span class="pane-title">Iteration log · final fit</span></div>
        <div class="pane-body">${table(['Round', 'Objective', 'Trades', 'Win rate', 'Avg R', 'Next-candle acc.', 'Bar', 'Changes'],
          r.rounds.map((x) => [x.round === 0 ? '0 (equal weights)' : `${x.round}${x.pass === 'fine' ? ' (fine)' : ''}`, num(x.objective), x.trades, pctAbs(x.winRate), signed(x.avgR, 3), pctAbs(x.accuracy), x.theta, x.changes.length ? x.changes.map((ch) => `${ch.signal} ${typeof ch.from === 'number' ? signed(ch.from, 2) : ch.from}→${typeof ch.to === 'number' ? signed(ch.to, 2) : ch.to}`).join(', ') : '—']))}
        </div></section>
      </div>

      <section class="pane"><div class="pane-head"><span class="pane-title">Per coin · holdout · final formula</span></div>
      <div class="pane-body">${table(['Coin', 'Trades', 'Win rate', 'Avg R', 'Total R', 'Profit factor', 't-stat', 'Next-candle acc.', 'Return @1% risk'], r.perCoin.map((p) => statRow(p.symbol.replace('USDT', ''), p.holdout, be)))}</div></section>

      <div class="grid2">
        <section class="pane"><div class="pane-head"><span class="pane-title">Are the probabilities honest? · holdout</span></div>
        <div class="pane-body">${table(['Predicted "works out"', 'Actually worked out', 'Trades'], r.calibration.holdout.buckets.map((b) => [pctAbs(b.predicted), `<span class="${b.actual >= b.predicted ? 'g' : 'r'}">${pctAbs(b.actual)}</span>`, b.n]))}
          <p class="note">Brier ${num(r.calibration.holdout.brier, 4)} (lower is better). Probabilities were calibrated per exit setup on the train period only.</p>
        </div></section>
        <section class="pane"><div class="pane-head"><span class="pane-title">Latest holdout trades · final formula</span></div>
        <div class="pane-body">${table(['Entered', 'Coin', 'Side', 'Exit setup', 'Entry', 'Exit', 'Result', 'R', 'P(works)', 'Risk'], r.sampleTrades.map((t) => [dt(t.t), t.symbol.replace('USDT', ''), `<span class="${t.side > 0 ? 'g' : 'r'}">${t.side > 0 ? 'LONG' : 'SHORT'}</span>`, comboLabel(c.combos[t.combo]), fmtPrice(t.entry), fmtPrice(t.exit), t.kind === 1 ? 'target' : t.kind === -1 ? 'stop' : t.kind === 2 ? 'trailed out' : 'timeout', `<span class="${cls(t.R)}">${signed(t.R, 2)}</span>`, pctAbs(t.p, 0), pctAbs(t.risk, 2)]))}</div></section>
      </div>

      <section class="pane"><div class="pane-head"><span class="pane-title">Method</span></div>
      <div class="pane-body">
        <p><b>Signals.</b> ${Sg.SIGNALS.length} sub-signals in ${Sg.GROUPS.length} groups, each scaled to −1…+1: ${Sg.SIGNALS.map((s) => s.label).join(', ')}. The news group uses the Crypto Fear &amp; Greed index (daily since 2018${r.hasFng ? '' : ' — missing in this run, run update-data.cmd'}) and the FOMC decision calendar; both have full history, so they are tested like everything else. Live headlines and your manual event bias have no history and are layered on top in the terminal, untested.</p>
        <p><b>Exit setups.</b> ${Object.keys(c.combos).length} candidates: stops of ${S.atrStops.join(', ')} × ATR(14) with or without a move to breakeven at +1R, a stop just beyond the nearest swing support / resistance (kept between 1 and 3 ATR), or a trailing stop of ${S.trailStops.join(' / ')} × ATR behind the best price; targets of ${S.rrFixed.map((x) => '1:' + x).join(', ')} the stop (trailing setups also with no fixed target); time-out after ${c.maxBars} bars (marked to market). ${c.feePct}% fee per side. Results in R = multiples of the initial stop distance. Within a candle the stop is checked before the target and before any trailing / breakeven move (conservative). The daily-chart context signals use only daily candles that closed before the bar opened.</p>
        <p><b>Tuning.</b> Start with every weight at +1. Each round, for every signal try −${S.step}, +${S.step}, 0 and a sign flip, keep whichever improves the objective (t-statistic of R per trade) by at least ${S.minGain}, then re-pick the bars (long and short bars can differ). Stop when a round improves by less than 1% or after ${S.maxRounds} rounds, then up to ${S.fineRounds} finer rounds with steps of ${S.fineStep}. Drop any weight whose removal costs less than 1%. A formula must fire on at least 1% of bars (and ${S.minTrades} times) to count.</p>
        <p><b>Choosing without peeking.</b> Every exit setup's weights are tuned on ${date(r.windows.trainStart)} → ${date(r.windows.validationStart)} only and judged on ${date(r.windows.validationStart)} → ${date(r.windows.holdoutStart)} against plain equal weights; the best out-of-sample variant wins and is refitted on the whole train period. The exit policy (per-situation stop / target, chosen by lower-confidence-bound R with at least ${S.minCellTrades} trades per situation) is learned on the fit half and kept only if it beats the fixed setup on the validation half, then relearned on the whole train period. Probabilities are calibrated per exit setup on train.</p>
        <p><b>Honesty.</b> Every "holdout" number comes from ${date(r.windows.holdoutStart)} onward, which was never used to fit anything. It has, however, been looked at several times while this engine was being developed (each redesign was judged partly on it), so it is not perfectly untouched; the "since ${date(r.windows.recentStart)}" slice is the least-consulted part and the best guide to what to expect live. The ML input was itself retrained weekly and only ever predicted bars after its training window.</p>
      </div></section>`;

    equitySvg($('#eq'), r.equity, Date.parse(r.windows.holdoutStart + 'T00:00:00Z'), Date.parse(r.windows.end));
  }

  $('#report').addEventListener('click', (e) => {
    const b = e.target.closest('button[data-tf]');
    if (!b) return;
    current = b.dataset.tf;
    render();
  });
  $('#run').addEventListener('click', start);
  const q = new URLSearchParams(location.search);
  if (q.has('tf')) document.querySelectorAll('input[type=checkbox]').forEach((c) => (c.checked = q.get('tf').split(',').includes(c.value)));
  if (q.has('coins')) document.querySelectorAll('input[name=coins]').forEach((c) => (c.checked = c.value === q.get('coins')));
  try { render(); } catch (err) { log('Could not render saved results: ' + err.message); }
  if (q.has('autorun')) start();
})();
